### ISSUE TITLE
Removing old installation fails with permission denied

### ISSUE THREAD

**Issue by LillyWho** [int-72h/oflauncher-rei#9]
I've got UAC completely disabled and running on an administrator account, so this shouldn't be happening:

`PS C:\Users\Lilly\oflauncher-rei> C:\Python310\python.exe .\gui.py
Traceback (most recent call last):
  File "C:\Users\Lilly\oflauncher-rei\gui.py", line 231, in <module>
    existing_game_check(ui, MainWindow)
  File "C:\Users\Lilly\oflauncher-rei\gui.py", line 197, in existing_game_check
    ofpath = getpath()
  File "C:\Users\Lilly\oflauncher-rei\steam.py", line 40, in getpath
    rmtree(target_path)
  File "C:\Python310\lib\shutil.py", line 747, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python310\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files (x86)\\Steam\\steamapps\\sourcemods\\open_fortress\\.git\\objects\\pack\\pack-a765432c57d0ad09ad2c95a3b5110789c8681f78.idx'`

**Comment by int-72h** [comment]
You need to remove the .git folder yourself.
